from __future__ import annotations
from pathlib import Path
import json
import shutil
import subprocess
import pandas as pd


def _latex_escape(s: object) -> str:
    text = str(s)
    reps = {"&":"\\&", "%":"\\%", "$":"\\$", "#":"\\#", "_":"\\_", "{":"\\{", "}":"\\}", "~":"\\textasciitilde{}", "^":"\\textasciicircum{}"}
    for a,b in reps.items():
        text = text.replace(a,b)
    return text

def _table_from_csv(path: Path, max_rows: int = 12) -> str:
    if not path.exists():
        return "File not generated."
    df = pd.read_csv(path).head(max_rows)
    cols = list(df.columns)
    spec = "l" * len(cols)
    lines = ["\\begin{tabular}{" + spec + "}", "\\hline"]
    nl = r"\\"
    lines.append(" & ".join(_latex_escape(c) for c in cols) + " " + nl)
    lines.append("\\hline")
    for _, row in df.iterrows():
        lines.append(" & ".join(_latex_escape(f"{v:.4g}" if isinstance(v, float) else v) for v in row) + " " + nl)
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    body = "\n".join(lines)
    return "\\begin{center}\\scriptsize\\resizebox{\\linewidth}{!}{%\n" + body + "\n}\\end{center}"

def make_report(root: str | Path, results: str | Path, figures: str | Path, out: str | Path) -> dict[str, object]:
    root = Path(root); results = Path(results); figures = Path(figures); out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    sections = out / "sections"; sections.mkdir(exist_ok=True)
    decision_path = root / "reproducibility" / "decision_register.json"
    decision = json.loads(decision_path.read_text()) if decision_path.exists() else {"status":"unknown", "reason":"decision file missing", "route_scores":{}}
    # copy figures into manuscript for stable relative paths
    fig_dir = out / "figures"; fig_dir.mkdir(exist_ok=True)
    for p in figures.rglob("*.png"):
        shutil.copy2(p, fig_dir / p.name)
    validation_csv = root / "tables" / "validation" / "validation_summary.csv"
    opt_csv = root / "tables" / "paper_lite" / "optimization_summary.csv"
    threshold_csv = root / "tables" / "paper_lite" / "threshold_table.csv"
    readiness_csv = root / "tables" / "paper_lite" / "paper_readiness_checklist.csv"
    (out / "macros.tex").write_text("\\newcommand{\\Jperp}{J_\\perp}\n\\newcommand{\\ph}{p_h}\n", encoding="utf-8")
    (out / "references.bib").write_text((root / "references.bib").read_text(encoding="utf-8") if (root/"references.bib").exists() else "", encoding="utf-8")
    (out / "latexmkrc").write_text("$pdf_mode=1;\n$interaction='nonstopmode';\n", encoding="utf-8")
    main = r"""
\documentclass[10pt]{article}
\usepackage[a4paper,margin=0.75in]{geometry}
\usepackage{graphicx,booktabs,amsmath,amssymb,longtable,array}
\usepackage[hidelinks]{hyperref}
\usepackage{xcolor}
\usepackage{float}
\input{macros.tex}
\title{Hole-Aware XXZ Squeezing Engine: Paper-Lite Generated Report}
\author{Generated by the HAXS research engine}
\date{\today}
\begin{document}
\maketitle
\begin{abstract}
This report is generated from actual laptop-scale runs of the HAXS engine. It implements exact diagonalization checks, a DTWA-like semiclassical engine, stochastic mobile-hole surrogate trajectories, spin-density fields, low-dimensional inverse design, empirical threshold scans, reproducibility manifests, and an evidence-based kill/no-kill decision. The results are smoke/paper-lite only and are not publication-grade evidence.
\end{abstract}
\tableofcontents
\section{Executive summary and decision}
\textbf{Decision:} DECISION_STATUS.\\
\textbf{Reason:} DECISION_REASON.

\begin{figure}[H]\centering\includegraphics[width=0.8\linewidth]{figures/decision_summary.png}\caption{Route scores used by the decision engine.}\end{figure}

\section{Model and methods}
The engine uses normalized units with $\Jperp=1$. Model 0 is a nearest-neighbour spin-1/2 XXZ Hamiltonian. Model 1 adds Bernoulli or fixed-count static vacancies. Model 2 adds stochastic mobile holes as random walkers that disrupt active bonds and density fields. Model 3 adds $h_i^{\rm sd}=\lambda_{\rm sd}\sum_{j\in\partial i}(1-n_j)$. Model 4 adds global echo, ramp, gradient, hold-time, and post-selection controls. The mobile-hole model is a controlled surrogate, not a full quantum $t$-$J$ calculation.

\begin{figure}[H]\centering\includegraphics[width=0.9\linewidth]{figures/model_hierarchy.png}\caption{Implemented model hierarchy.}\end{figure}

\section{Validation}
\begin{figure}[H]\centering\includegraphics[width=0.9\linewidth]{figures/validation_sanity.png}\caption{Validation metrics generated by the validation pipeline.}\end{figure}
\noindent Validation table:\\
VALIDATION_TABLE

\section{Mechanism decomposition}
The mechanism pipeline compares ideal, static-vacancy, mobile-only, spin-density-only, and full mobile+spin-density surrogates. Distances are finite-size and seed-limited.
\begin{figure}[H]\centering\includegraphics[width=0.9\linewidth]{figures/mechanism_decomposition.png}\caption{Mechanism decomposition squeezing curves.}\end{figure}

\section{Inverse design}
The optimizer uses deterministic random search over echo time, hold time, ramp duration, final anisotropy, and gradient strength. Train and test seeds are disjoint.
\begin{figure}[H]\centering\includegraphics[width=0.85\linewidth]{figures/inverse_design.png}\caption{Baseline versus best inverse-designed protocol in paper-lite runs.}\end{figure}
\noindent Optimization summary:\\
OPT_TABLE

\section{Threshold map}
The threshold scan is an empirical finite-grid map. It is restricted to the tested sizes, stochastic-hole surrogate, normalized couplings, and global controls. It is not a theorem.
\begin{figure}[H]\centering\includegraphics[width=0.9\linewidth]{figures/threshold_map.png}\caption{Restricted threshold scan.}\end{figure}
\noindent Threshold table excerpt:\\
THRESHOLD_TABLE

\section{Anti-scoop and publication strategy}
The narrow novelty claim supported by this artifact is an open, reproducible software engine that separates static vacancies, stochastic mobile-hole bond disruption, and density-induced longitudinal fields in a Ketterle-regime-inspired XXZ squeezing problem. The current generated data do not justify a PRL-level constructive recovery claim. The safest paper route is a methods/diagnostic note only after larger ED/DTWA/tensor-network checks, stronger uncertainty estimates, and finite-size tests.

\section{Limitations and next steps}
The present results are paper-lite. They do not use private experimental parameters. They do not include full quantum mobile holes, tensor-network validation, or paper-grade finite-size scaling. Required next commands are listed in the generated next-run table.\\
READINESS_TABLE

\section{Reproducibility}
All result files, figures, tables, command history, environment, SHA256 hashes, and decision JSON are included in the repository under \texttt{reproducibility/}. The report was compiled from generated tables and figures.

\section{Bibliography note}
The repository includes a BibTeX file copied from the proposal package. This generated report avoids invoking BibTeX because the execution environment lacks the BibTeX executable; the source bibliography remains available for Overleaf or a full TeX installation.
\begin{thebibliography}{9}
\bibitem{Lee2025} Yoo Kyung Lee, Maxwell Block, Hanzhen Lin, Vitaly Fedoseev, Philip J. D. Crowley, Norman Y. Yao, and Wolfgang Ketterle, observation of spin squeezing with contact interactions in one- and three-dimensional easy-plane magnets, arXiv:2409.17398 and Physical Review Letters record.
\bibitem{KitagawaUeda1993} Masahiro Kitagawa and Masahito Ueda, squeezed spin states, Physical Review A 47, 5138 (1993).
\bibitem{Wineland1994} D. J. Wineland and collaborators, spin squeezing and reduced quantum noise in spectroscopy, Physical Review A 50, 67 (1994).
\end{thebibliography}
\end{document}
"""
    main = main.replace("DECISION_STATUS", _latex_escape(decision.get("status", "unknown")))
    main = main.replace("DECISION_REASON", _latex_escape(decision.get("reason", "unknown")))
    main = main.replace("VALIDATION_TABLE", _table_from_csv(validation_csv))
    main = main.replace("OPT_TABLE", _table_from_csv(opt_csv))
    main = main.replace("THRESHOLD_TABLE", _table_from_csv(threshold_csv, max_rows=10))
    main = main.replace("READINESS_TABLE", _table_from_csv(readiness_csv, max_rows=20))
    (out / "main.tex").write_text(main, encoding="utf-8")
    # Clean stale auxiliary files before compiling. In this environment latexmk is
    # available but bibtex is not; stale .aux/.fdb files can make latexmk try a
    # BibTeX run even though this generated report uses thebibliography.
    for ext in ["aux", "bbl", "blg", "fdb_latexmk", "fls", "log", "out", "toc"]:
        stale = out / f"main.{ext}"
        if stale.exists():
            stale.unlink()
    log = ""
    if shutil.which("pdflatex"):
        logs = []
        for _ in range(2):
            proc = subprocess.run(["pdflatex", "-interaction=nonstopmode", "main.tex"], cwd=out, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=120)
            logs.append(proc.stdout)
        log = "\n--- PDFLATEX PASS ---\n".join(logs)
    elif shutil.which("latexmk"):
        proc = subprocess.run(["latexmk", "-pdf", "-interaction=nonstopmode", "main.tex"], cwd=out, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=120)
        log = proc.stdout
    else:
        log = "LaTeX unavailable; source generated only."
    (out / "build.log").write_text(log, encoding="utf-8")
    return {"pdf_exists": (out / "main.pdf").exists(), "build_log": str(out / "build.log")}
