#!/usr/bin/env python
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))

import argparse, json, subprocess, sys, os
from pathlib import Path
from haxs.reporting.latex import make_report
from haxs.io.manifest import collect_manifest, write_manifest, package_versions
from haxs.io.hashes import write_sha256_listing, sha256_file
from haxs.io.result_store import ensure_dir, save_dataframe
from haxs.utils.logging import append_log
import pandas as pd

ap=argparse.ArgumentParser(); ap.add_argument('--results', default='results'); ap.add_argument('--figures', default='figures'); ap.add_argument('--out', default='manuscript'); args=ap.parse_args()
# readiness/next command tables
ensure_dir(ROOT/'tables/paper_lite')
readiness=pd.DataFrame([
 {'item':'imports cleanly','status':'generated by tests','grade':'validation'},
 {'item':'smoke pipeline','status':'ran if results/smoke exists','grade':'smoke'},
 {'item':'mechanism decomposition','status':'paper-lite generated','grade':'paper-lite'},
 {'item':'inverse design','status':'paper-lite generated','grade':'paper-lite'},
 {'item':'threshold map','status':'paper-lite generated','grade':'paper-lite'},
 {'item':'paper-grade finite-size scaling','status':'not run in this environment','grade':'not claimed'},
 {'item':'full quantum mobile holes','status':'not implemented beyond ED anchor/surrogate','grade':'extension'},
])
save_dataframe(ROOT/'tables/paper_lite/paper_readiness_checklist.csv', readiness)
next_cmds=pd.DataFrame([
 {'purpose':'repeat tests','command':'python scripts/run_tests.py'},
 {'purpose':'paper-full mechanism','command':'python scripts/run_mechanism_decomposition.py --config configs/paper_full/mechanism_decomposition_full.yaml --out results/paper_full/mechanism'},
 {'purpose':'paper-full optimization','command':'python scripts/run_inverse_design.py --config configs/paper_full/optimization_full.yaml --out results/paper_full/optimization'},
 {'purpose':'paper-full threshold','command':'python scripts/run_threshold_map.py --config configs/paper_full/threshold_map_full.yaml --out results/paper_full/threshold'},
 {'purpose':'regenerate figures','command':'python scripts/make_all_figures.py --results results --out figures'},
 {'purpose':'regenerate report','command':'python scripts/make_report.py --results results --figures figures --out manuscript'},
])
save_dataframe(ROOT/'tables/paper_lite/next_run_command_table.csv', next_cmds)
result=make_report(ROOT, ROOT/args.results, ROOT/args.figures, ROOT/args.out)
# environment lock
(ROOT/'reproducibility/environment_lock.md').write_text('# Environment lock\n\n' + '\n'.join(f'- {k}: {v}' for k,v in package_versions().items()) + '\n', encoding='utf-8')
decision='unknown'; dp=ROOT/'reproducibility/decision_register.json'
if dp.exists(): decision=json.loads(dp.read_text()).get('status','unknown')
manifest=collect_manifest(ROOT, decision_status=decision, tests={'transcript':str(ROOT/'reproducibility/test_transcript.txt')}, commands=(ROOT/'reproducibility/command_history.sh').read_text().splitlines() if (ROOT/'reproducibility/command_history.sh').exists() else [])
write_manifest(ROOT/'reproducibility/manifest.json', manifest)
write_sha256_listing(ROOT, ROOT/'reproducibility/sha256.txt')
append_log(ROOT/'reproducibility/run_log.md', f'report generated; pdf_exists={result["pdf_exists"]}')
with (ROOT/'reproducibility/command_history.sh').open('a', encoding='utf-8') as f: f.write(f'python scripts/make_report.py --results {args.results} --figures {args.figures} --out {args.out}\n')
print(result)
